anchor_version = "0.29.0"

[workspace]
members = ["programs/amm"]

[features]
seeds = false

[programs.mainnet]
amm = "EkAyJTwXawoFGnfFeqpLNS3dM6BA3AX5xqH8ywFmB4a1"

[programs.devnet]
amm = "HfHRndGpS82B5HtEnTeA4fpTVdQqnn8ZYjaENt9oDZJY"

[registry]
url = "https://github.com/NovaDexDev/novadex-clmm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json" 
